language: node_js
node_js:
- stable
addons:
  apt:
    packages:
    - sshpass
install:
- npm install
script:
- npm run test:unit
- npm run build
branches:
  only:
  - master
env:
  global:
  - secure: Vp1JlGotjdhhwwUnM1Yg7oFetNIeXrqhQ6MTAF9Njciu3qMiydvD168uA/DheCS7ET61YL/cNd+231ICxHDFxiIRaebkdwkCS6xzqlh5exQ92vkJPSc0c/mK8PkrggBLIx6Xf012Rb/mLzrs5lCpJn6xB0JtUg5gTiOqw52/Xk4LEsiiCqQvTGXFIOOiu+D0AKvyqz5ctuCo0T6Ej+A9LM71TmU9nUsx619hEseqCooflSZdPqPXBLsLvjsy7PTXBlCqLBWBrpV4Djs++yD8VLcw+XMpjo6Ca6ilSloxyUyVuYfzxkZGl0kXHq7Acc/1BaRo85gsAClZmASdfFOceG8CIUDKkPLbMm5dwy2t0TOYv7elrp8RGAYYjQYhVF+X/mJIVGH3Vj6hx5i6KxhmFgyruKyam/u8MyMFhbB6d7si6GfyKuuxi7EAc/g2gFFIS8Y1qI2G7KNWfI98yQSUNq2pRtGOWCPzilKG9S019adGs2Y92vWqU9dfaPJx3u2ZNUNrXTNUlPMPuWWr8r+wCNcG3hL1BPWXLUbgBY/kaVQzNRqQe+LCXOYm/mUN1FOIZPm0DwD9fmX/4mkgbqXBvEdWJDcQTFZf7vFjVvA7jqFwOLZkTfeDjLf/VhM6wvLsx/iQBS88PZ1HnjPyD1BoKUgz5yzyUW5qYuLCiSFZhLw=
  - secure: umK502cLOC4d0uj1FPWgmwxcaHyequbbhfBvk7uKdnhhR2itKRrAggSTkLymDf7/QhcyvQD9gtO5TzyUKPFhwssgkI/HnzFKk+r5ZD0hwMhOYYZtZ7aBxCMvTEkpRIj39lfA+Lom6P5mP6EGyzxVdzfnQTg68atFaAyjht2udVIesg5z/9c5YLu6zljsJp7/zepnEY2owaBziwJFtaPPVT7/xQhqS3nxwZvXj9YtAvGKOZ8uZnxXrQorX7pDXL3e0eZQllUdQDihGmvYqoDl1CPeYs/SZHEgYhJPq/Gk0MdHJCc3CmCAp796HwiY8/UVJXVvP3NcizWI/elf+40MHeid4+qnkvYLznYUDzKtxszYxDaecwXdzgNWSOnpvWQP9jxAuOWCFvufoKxc3UdjXheS1La5xlrs+G8e9tHrtvMhJsGnTSKvhn1y7AnQE98hLHbIsgM3jL7av0ORWUFLdc/dzinZhMHawntXPzteXIxDUAB0wKZbHKJKY/gAwk0jeENJbA5b9joDWr+1qM4niDurKojOvH6sAE58c3jSk8snSXGG2hkP0CkiDyOKoKubJftuKdRJAH1Zb11GKBue4C+/iHqX/Loc6yY9aTwSiU+vloHJW4BpJ+D0llEDNV79MIGXDIOscdiMaUUaY3dLnJh0Q2cUDKAE7bGQRAMqfw4=
  - secure: hsl9Y2TUS2+MbhEfHSDqkIB9Cr+Com+zlQx5ZhF0BvxnYuureswUsTOv14dyScJfuhF9+UylzIx0Mgvn2JQj6w09Id28b/CV2hukZ0BZhp+XMhG+Gsayiv7a+UmoguZKC2KR1OxovpDtqkd1KXHeRDNt9H47fpzsqWhEsl3c6m+DSavfb2R8icunsmbs9pLLUlw/dRZcOUbHPcVl3HRH/QM5N96D+R9irTAQXB8GP7FdGclundNuRgle1CmCNPawZ8xH5viKL8RwpeVJZaqyIDpDnDMSqjTxoYTiGrf2LCuH2zQ4v/BGcAthKD26Vo+bKNF0NbyPa5YIaHcN9Rqb8Y8Gny7V9EAcp+XYQQRp2wKQ4XjRQJBZpGXjUR2+tBBcjAeUB+/tAxLeL+nYafYQLgF2mEW8UEKCYokCzmEr+lsi3BFkjqFz7JmpOoexh02htBHsK0BybD+b3D2djE8p8W/jmlpnse3CGSBWe40J/PVb6G2FA4vPEjQlOLWAurkAju84Om9v8n3HCmutPWe4o/eCW4mS31bPltLevv/rQTmR/Vj3P8UDx/UAyIcuQZBfADF5n1Niq6hGncRhzgDndMgXQf48rBrcnlwvv986l80BMaGm+vNY5q+W/Zi3Cr/xdj/rDOFZorLMEmj0xd0KnNaTPqGrXSHMMFAghSx80L8=
after_success:
- export SSHPASS=$SSHPASS
- sshpass -p$SSHPASS scp -r 2018 $SSHUSER@$SSHHOST:/home/katajist/public/html/testi
